frame_id: map
default_direction: forward
default_densify_ds: 0.0
paths:
  1:
    direction: backward
    points:
    - - 0.325
      - 2.985
    - - 0.325
      - 1.985
    - - 0.325
      - 0.985
    - - 0.325
      - 0.0
    - - 0.325
      - -0.2
    - - 0.65
      - -0.325
    - - 1.65
      - -0.325
    - - 2.65
      - -0.325
    - - 3.65
      - -0.325
    - - 4.06
      - -0.325
    - - 4.35
      - -0.2
    - - 4.35
      - 0.0
    - - 4.35
      - 0.885
  2:
    direction: backward
    points:
    - - 4.35
      - 0.885
    - - 4.35
      - 1.5
    - - 4.35
      - 2.0
    - - 4.35
      - 2.5
    - - 4.35
      - 3.0
    - - 4.35
      - 3.5
    - - 4.35
      - 4.0
    - - 4.35
      - 4.5
    - - 4.38
      - 5.0
    - - 4.38
      - 5.5
    - - 4.38
      - 6.0
    - - 4.38
      - 6.5
    - - 4.38
      - 7.0
    - - 4.38
      - 7.63
  3:
    direction: forward
    points:
    - - 4.38
      - 7.63
    - - 4.38
      - 7.0
    - - 4.38
      - 6.5
    - - 4.38
      - 6.0
    - - 4.38
      - 5.5
    - - 4.38
      - 5.0
    - - 4.38
      - 4.5
    - - 4.35
      - 4.0
    - - 4.35
      - 3.5
    - - 4.35
      - 3.0
    - - 4.35
      - 2.5
    - - 4.35
      - 2.0
    - - 4.35
      - 1.5
    - - 4.35
      - 0.885
  4:
    direction: forward
    points:
    - - 4.35
      - 0.885
    - - 4.35
      - 0.0
    - - 4.35
      - -0.2
    - - 4.06
      - -0.325
    - - 3.65
      - -0.325
    - - 2.65
      - -0.325
    - - 1.65
      - -0.325
    - - 0.65
      - -0.325
    - - 0.325
      - -0.2
    - - 0.325
      - 0.0
    - - 0.325
      - 0.985
    - - 0.325
      - 1.985
    - - 0.325
      - 2.985
  5:
    direction: forward
    points:
    - - 0.0
      - 0.0
    - - 0.0
      - 0.5
  6:
    direction: backward
    points:
    - - 0.0
      - 0.5
    - - 0.0
      - 0.0
  108:
    direction: forward
    generated_from:
      station_start: OmniFire
      station_end: LC
    points:
    - - 4.35
      - 0.885
    - - 4.355
      - 0.885
    - - 4.355
      - 0.325
    - - 4.345
      - -0.325
    - - 3.345
      - -0.325
    - - 2.345
      - -0.325
    - - 1.345
      - -0.325
    - - 0.65
      - -0.325
    - - 0.325
      - 0.325
    - - 0.325
      - 1.325
    - - 0.325
      - 2.325
    - - 0.325
      - 2.985
  118:
    direction: backward
    generated_from:
      station_start: LC
      station_end: OmniFire
    points:
    - - 0.325
      - 2.985
    - - 0.325
      - 1.985
    - - 0.325
      - 0.985
    - - 0.325
      - 0.325
    - - 0.65
      - -0.325
    - - 1.65
      - -0.325
    - - 2.65
      - -0.325
    - - 3.65
      - -0.325
    - - 4.345
      - -0.325
    - - 4.355
      - 0.325
    - - 4.355
      - 0.885
    - - 4.35
      - 0.885
  112:
    direction: forward
    generated_from:
      station_start: Synthesis
      station_end: LC
      generator: poi_graph_v2
    points:
    - - 4.35
      - 0.885
    - - 4.353
      - 0.885
    - - 4.353
      - 0.075
    - - 4.309
      - -0.145
    - - 4.178
      - -0.279
    - - 3.953
      - -0.325
    - - 2.953
      - -0.325
    - - 2.337
      - -0.325
    - - 1.337
      - -0.325
    - - 0.723
      - -0.325
    - - 0.502
      - -0.281
    - - 0.369
      - -0.151
    - - 0.323
      - 0.075
    - - 0.323
      - 1.075
    - - 0.323
      - 2.075
    - - 0.323
      - 2.985
    - - 0.325
      - 2.985
  119:
    direction: backward
    generated_from:
      station_start: LC
      station_end: Synthesis
      generator: poi_graph_v2
    points:
    - - 0.325
      - 2.985
    - - 0.323
      - 2.985
    - - 0.323
      - 1.985
    - - 0.323
      - 0.985
    - - 0.323
      - 0.075
    - - 0.366
      - -0.145
    - - 0.497
      - -0.279
    - - 0.723
      - -0.325
    - - 1.723
      - -0.325
    - - 2.337
      - -0.325
    - - 3.337
      - -0.325
    - - 3.953
      - -0.325
    - - 4.173
      - -0.281
    - - 4.306
      - -0.151
    - - 4.353
      - 0.075
    - - 4.353
      - 0.885
    - - 4.35
      - 0.885
  121:
    direction: backward
    generated_from:
      station_start: Battery
      station_end: Synthesis
      generator: poi_graph_v2
    points:
    - - 4.38
      - 7.63
    - - 4.362
      - 7.463
    - - 4.357
      - 7.403
    - - 4.354
      - 7.343
    - - 4.353
      - 7.282
    - - 4.353
      - 6.282
    - - 4.353
      - 5.997
    - - 4.353
      - 4.997
    - - 4.353
      - 3.997
    - - 4.353
      - 2.997
    - - 4.353
      - 1.997
    - - 4.353
      - 0.997
    - - 4.353
      - 0.885
    - - 4.35
      - 0.885
  122:
    direction: backward
    generated_from:
      station_start: Battery
      station_end: LC
      generator: poi_graph_v2
    points:
    - - 4.38
      - 7.63
    - - 4.362
      - 7.463
    - - 4.357
      - 7.403
    - - 4.354
      - 7.343
    - - 4.353
      - 7.282
    - - 4.353
      - 6.397
    - - 4.309
      - 6.177
    - - 4.178
      - 6.044
    - - 3.953
      - 5.997
    - - 2.953
      - 5.997
    - - 2.337
      - 5.997
    - - 1.337
      - 5.997
    - - 0.723
      - 5.997
    - - 0.502
      - 5.954
    - - 0.369
      - 5.823
    - - 0.323
      - 5.597
    - - 0.323
      - 4.597
    - - 0.323
      - 3.597
    - - 0.323
      - 2.985
    - - 0.325
      - 2.985
  123:
    direction: forward
    generated_from:
      station_start: Synthesis
      station_end: Battery
      generator: poi_graph_v2
    points:
    - - 4.35
      - 0.885
    - - 4.353
      - 0.885
    - - 4.353
      - 1.885
    - - 4.353
      - 2.885
    - - 4.353
      - 3.885
    - - 4.353
      - 4.885
    - - 4.353
      - 5.885
    - - 4.353
      - 5.997
    - - 4.353
      - 6.997
    - - 4.353
      - 7.282
    - - 4.354
      - 7.342
    - - 4.357
      - 7.401
    - - 4.362
      - 7.463
    - - 4.38
      - 7.63
  124:
    direction: backward
    generated_from:
      station_start: LC
      station_end: Battery
      generator: poi_graph_v2
    points:
    - - 0.325
      - 2.985
    - - 0.323
      - 2.985
    - - 0.323
      - 3.985
    - - 0.323
      - 4.985
    - - 0.323
      - 5.597
    - - 0.366
      - 5.818
    - - 0.497
      - 5.951
    - - 0.723
      - 5.997
    - - 1.723
      - 5.997
    - - 2.337
      - 5.997
    - - 3.337
      - 5.997
    - - 3.953
      - 5.997
    - - 4.173
      - 6.041
    - - 4.306
      - 6.172
    - - 4.353
      - 6.397
    - - 4.353
      - 7.282
    - - 4.354
      - 7.342
    - - 4.357
      - 7.401
    - - 4.362
      - 7.463
    - - 4.38
      - 7.63
