#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'bno055==0.4.1','console_scripts','bno055'
__requires__ = 'bno055==0.4.1'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('bno055==0.4.1', 'console_scripts', 'bno055')()
    )
