mob_rob_loca:
  ros__parameters:
    tracks:
      # Route Gauche (t_x = 0.0)
      "1":
        t_x: 0.0
        t_y: -5.675
        yaw: 0.0

      "2":
        t_x: 0.0
        t_y: -3.675
        yaw: 0.0

      "3":
        t_x: 0.0
        t_y: -1.675
        yaw: 0.0

      "4":
        t_x: 0.0
        t_y: 0.325
        yaw: 0.0
        markers:
          "645":
            t_x: 0.0
            t_y: 0.0
            yaw: 0.0

      "5":
        t_x: 0.0
        t_y: 2.325
        yaw: 0.0

      "6":
        t_x: 0.0
        t_y: 4.325
        yaw: 0.0

      # Route Droite (t_x = 4.03)
      "7":
        t_x: 4.03
        t_y: -7.675
        yaw: 0.0
      "8":
        t_x: 4.03
        t_y: -5.675
        yaw: 0.0

      "9":
        t_x: 4.03
        t_y: -3.675
        yaw: 0.0

      "10":
        t_x: 4.03
        t_y: -1.675
        yaw: 0.0

      "11":
        t_x: 4.03
        t_y: 0.325
        yaw: 0.0
        markers:
          "9":
            t_x: 0.492
            t_y: 1.193
            yaw: 0
          "10":
            t_x: 0.147
            t_y: 1.193
            yaw: 0

      "12":
        t_x: 4.03
        t_y: 2.325
        yaw: 0.0
        markers:
          "5":
            t_x: 0.493
            t_y: 1.647
            yaw: 0
          "6":
            t_x: 0.137
            t_y: 1.647
            yaw: 0
          "7":
            t_x: 0.479
            t_y: 0.247
            yaw: 0
          "8":
            t_x: 0.126
            t_y: 0.247
            yaw: 0

      "13":
        t_x: 4.03
        t_y: 4.325
        yaw: 0.0
        markers:
          "3":
            t_x: 0.489
            t_y: 1.165
            yaw: 0
          "4":
            t_x: 0.144
            t_y: 1.165
            yaw: 0

      "14":
        t_x: 4.03
        t_y: 6.325
        yaw: 0.0

      # Pont Haut (t_y = 5.675)
      "15":
        t_x: 4.03
        t_y: 5.675
        yaw: 1.5708

      "16":
        t_x: 2.85
        t_y: 5.675
        yaw: 1.5708

      "17":
        t_x: 1.85
        t_y: 5.675
        yaw: 1.5708

      # Pont Bas (t_y = 0.0)
      "18":
        t_x: 0.65
        t_y: 0.0
        yaw: -1.5708

      "19":
        t_x: 1.85
        t_y: 0.0
        yaw: -1.5708

      "20":
        t_x: 2.85
        t_y: 0.0
        yaw: -1.5708
