#mob_rob_loca:
#  ros__parameters:
#    aruco_params:
#      "11":
#        t_x: 4.352
#        t_y: 6.368
#        yaw: 1.57
#      "618":
#        t_x: 4.402
#        t_y: 7.358
#        yaw: 1.57
#      "645":
#        t_x: 0.0
#        t_y: 0.0
#        yaw: 0.0
#      "614":
#        t_x: 4.38
#        t_y: 4.56
#        yaw: 1.57

mob_rob_loca:
  ros__parameters:
    tracks:
      "1":
        t_x: 0.0
        t_y: 0.335
        yaw: 0.0
        markers:
          "645":
            t_x: 0.0
            t_y: 0.0
            yaw: 0.0
#        markers:
#          "100":
#            t_x: 0.1625
#            t_y: 0.5
#            yaw: 1.57
#          "101":
#            t_x: 0.4875
#            t_y: 0.5
#            yaw: 1.57
#          "102":
#            t_x: 0.1625
#            t_y: 1.5
#            yaw: 1.57
#          "103":
#            t_x: 0.4875
#            t_y: 1.5
#            yaw: 1.57
      "2":
        t_x: 0.0
        t_y: 2.335
        yaw: 0.0
#        markers:
#          "104":
#            t_x: 0.1625
#            t_y: 0.5
#            yaw: 1.57
#          "105":
#            t_x: 0.4875
#            t_y: 0.5
#            yaw: 1.57
#          "106":
#            t_x: 0.1625
#            t_y: 1.5
#            yaw: 1.57
#          "107":
#            t_x: 0.4875
#            t_y: 1.5
#            yaw: 1.57
      "3":
        t_x: 0.0
        t_y: 4.335
        yaw: 0.0
      "4":
        t_x: 4.03
        t_y: 0.335
        yaw: 0.0
        markers:
          "9":
            t_x: 0.492
            t_y: 1.193
            yaw: 0
          "10":
            t_x: 0.147
            t_y: 1.193
            yaw: 0
      "5":
        t_x: 4.03
        t_y: 2.335
        yaw: 0.0
        markers:
          "5":
            t_x: 0.493
            t_y: 1.647
            yaw: 0
          "6":
            t_x: 0.137
            t_y: 1.647
            yaw: 0
          "7":
            t_x: 0.479
            t_y: 0.247
            yaw: 0
          "8":
            t_x: 0.126
            t_y: 0.247
            yaw: 0
      "6":
        t_x: 4.03
        t_y: 4.335
        yaw: 0.0
        markers:
          "3":
            t_x: 0.489
            t_y: 1.165
            yaw: 0
          "4":
            t_x: 0.144
            t_y: 1.165
            yaw: 0
