ur5-sfc: #RMN station
  pos_x: 4.41
  pos_y: 7.55
  yaw: 1.5708
  wp_x: 4.41
  wp_y: 4.69

ur5-omni: 
  pos_x: 4.175
  pos_y: 4.6
  yaw: 0.0
  wp_x: 4.41
  wp_y: 4.69

test:
  pos_x: 0.3
  pos_y: 0.0
  yaw: 0.751
